# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  #repository_dispatch:
    #types:
      #- my_event
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
          MYSQL_DATABASE: foo
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          NEW_DATABASE: new_db
    services:
      db:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{secrets.MYSQL_ROOT_PASSWORD}}
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Start MYSQL Server
        run: |
          echo "Starting MYSQL"
          mysqladmin --protocol=tcp -h localhost -P 3306 -u root -p ${{env.MYSQL_ROOT_PASSWORD}} ping &> /dev/null && break
          sleep 2
          
      - name: Create Database and Grant Full Permissions to User1
        run: |
          mysql --protocol=tcp -h localhost -P 3306 -u root -p ${{env.MYSQL_ROOT_PASSWORD}} -e "CREATE DATABASE IF NOT EXISTS ${NEW_DATABASE};"
          #mysql --protocol=tcp -h localhost -P 3306 -u root -p ${{env.MYSQL_ROOT_PASSWORD}} -e "CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';"
          #mysql --protocol=tcp -h localhost -P 3306 -u root -p ${{env.MYSQL_ROOT_PASSWORD}} -e "GRANT ALL PRIVILEGES ON ${NEW_DATABASE}.* TO '${MYSQL_USER}'@'%'; FLUSH PRIVILEGES;"
      #- name: Create Table and Insert Data
        #run: |
         # mysql --protocol=tcp -h localhost -P 3306 -u ${{ secrets.MYSQL_USER }} -p${{ secrets.MYSQL_PASSWORD }} ${NEW_DATABASE} -e "CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(50));"
         # mysql --protocol=tcp -h localhost -P 3306 -u ${{ secrets.MYSQL_USER }} -p${{ secrets.MYSQL_PASSWORD }} ${NEW_DATABASE} -e "INSERT INTO users (name) VALUES ('Alice'), ('Bob');"
      #- name: Query Data
       # run: |
        #  mysql --protocol=tcp -h localhost -P 3306 -u ${{ secrets.MYSQL_USER }} -p${{ secrets.MYSQL_PASSWORD }} ${NEW_DATABASE} -e "SELECT * FROM users;"

      
